WIP: Flashcards codebase improvements
vitaliiyn/flashcards pull request #1
Opened 2020-10-16 23:47 UTC by vitaliiyn

2020-10-19 00:04 UTC, IvanShamatov requested changes
Хорошо справился, отлично разобрался с самим приложением. Прикольно, что апгрейд рельсы не вызвал сильных болей. Я бы даже сказал, удивительно.
Я бы рекомендовал зафиксировать руками версии гемов.
Локали надо пофиксить везде.

2020-10-19 00:04 UTC, IvanShamatov commented on app/models/card.rb
> +    TranslationServices::TranslationChecker.new(self, user_translation).call
не думаю, что сервисов переводов будет много, но если уж делаешь неймспейс на них, то тогда нет смысла повторяться в названии самого класса

2020-10-19 00:04 UTC, IvanShamatov commented on app/models/card.rb
> +    TranslationServices::TranslationChecker.new(self, user_translation).call
в целом, поскольку логика теперь в другом месте, то можно было бы вообще этот метод из модели достать, и использовать напрямую в месте, где вызывался метод модели

2020-10-19 00:04 UTC, IvanShamatov commented on app/services/notification_services/pending_cards_notifier.rb
> +        CardsMailer.pending_cards_notification(user.email).deliver if user.cards.pending.any?
у этого сервиса большой недостаток не в том, что он лежит в модели, а в том, что он бегает по всем пользователям и для каждого делает пачку запросов.
По факту же нам нужно наоборот достать просроченные карточки и только по их пользователям разослать напоминалки

2020-10-19 00:04 UTC, IvanShamatov commented on app/services/translation_services/translation_checker.rb
> +        @card.update(sm_hash)
этот сервис не только проверяет но еще и мутирует данные. Я бы его назвал ProcessTranslation в таком случае, а еще лучше, если бы он не зависел от модели, получал на вход интервал, повторяения, ефактор, попытки, возвращал обратно sm_hash и мы бы в модели апдейтили нашу модель новыми данными, тем самым снизив связность сервиса от модели

2020-10-19 00:04 UTC, IvanShamatov commented on app/validators/text_difference_validator.rb
> +    record.errors[:original_text] << 'Вводимые значения должны отличаться.' if texts_eql?(record)
по всему проекту локальки есть, а тут текст на русском языке.

2020-10-19 00:04 UTC, IvanShamatov commented on spec/features/login_spec.rb
> +        .to have_content 'Вход не выполнен. Проверте вводимые E-mail и Пароль.'
тут тоже надо локали пофиксить

2020-10-19 00:06 UTC, IvanShamatov commented
https://stackoverflow.com/questions/62783381/github-actions-workflow-pgconnectionbad-could-not-connect-to-server-no-such 
вот эта штука должна помочь тебе справиться с гитхаб экшнс

2020-10-19 22:15 UTC, vitaliiyn commented on app/services/notification_services/pending_cards_notifier.rb
> +        CardsMailer.pending_cards_notification(user.email).deliver if user.cards.pending.any?
Да, ты прав. Не заметил это. Добавил витягивание `pending` карточек и групировку по их юзерам. А потом уже отправку писем тем юзерам. Также немного порефакторил скоупы карточек и место где они используються.
[Изменнения в этом коммите](https://github.com/vitaliiyn/flashcards/pull/1/commits/e627cf2ed792a1550016e592cef4eca031f93b7d)

2020-10-19 22:23 UTC, vitaliiyn commented on app/services/translation_services/translation_checker.rb
> +        @card.update(sm_hash)
Makes sense. Порефакторил таким образом. [Вот тут изменения](https://github.com/vitaliiyn/flashcards/pull/1/commits/d5361a69a65b416c47b52efe8955250d3c7baaad)
Таже собираюсь вынести вызов сервиса на уровень контроллера и изменит значения которые из него возвращаются, как собирался раньше и как ты предложил в другом коменте. 
Но так как это более значимый рефакторинг - займусь этим после всех изменений.

2020-10-19 22:25 UTC, vitaliiyn commented
Пофиксил GithubActions. Теперь прогоняется CI

2020-10-22 00:41 UTC, vitaliiyn commented on app/models/card.rb
> +    TranslationServices::TranslationChecker.new(self, user_translation).call
Вынес вызов сервиса с модели на уровень контроллера. Также пофиксил тесты, которые вызывали этот метод модели. [В этом коммите](https://github.com/vitaliiyn/flashcards/pull/1/commits/efb7650ce9d8231a24d1addd933ed5ccbe2ebb20)

2020-10-22 07:49 UTC, IvanShamatov approved these changes

2020-10-22 07:49 UTC, IvanShamatov commented on app/services/notification_services/pending_cards_notifier.rb
> +      @users = Card.includes(:user).pending.select(:user_id).distinct.map(&:user)
map(&:user) инстанцирует тебе N объектов юзера. А юзер это обычно самая жирная модель в проекте, хотя тебе вообще нужны только их email'ы. Можно еще легче сделать запрос

2021-11-16 21:00 UTC, merged